### ISSUE TITLE
Comparison with rust-signals

### ISSUE THREAD

**Issue by kellytk** [M-Adoo/rxRust#16]
Thanks for starting this project.  'FRP' is my favorite style to write software in.

I think that a comparison with https://github.com/Pauan/rust-signals would be helpful to include in the README or elsewhere.

**Comment by M-Adoo** [comment]
Thanks for your advice，I don't know much about this library now. But for 'FRP', [ReactiveX introduction](http://reactivex.io/intro.html) page maybe useful for you.

> It is sometimes called “functional reactive programming” but this is a misnomer. ReactiveX may be functional, and it may be reactive, but “functional reactive programming” is a different animal. One main point of difference is that functional reactive programming operates on values that change continuously over time, while ReactiveX operates on discrete values that are emitted over time. (See Conal Elliott’s work for more-precise information on functional reactive programming.)
