### ISSUE TITLE
`RawSubscribable` redesign

### ISSUE THREAD

**Issue by M-Adoo** [M-Adoo/rxRust#19]
For now `RawSubscribable` define like this:

```rust
pub trait RawSubscribable {
  /// The type of the elements being emitted.
  type Item;
  // The type of the error may propagating.
  type Err;

  fn raw_subscribe(
    self,
    subscribe: impl RxFn(RxValue<&'_ Self::Item, &'_ Self::Err>)
    + Send
    + Sync
    + 'static,
  ) -> Box<dyn Subscription + Send + Sync>;
}
```
We add bound `Sync + Send + 'static`  to `subscribe`, so all user code must be thread safe. So, we use so much  `Arc`, `Mutex`, `RwLock` or other wrapper for datas.  But in many times,  code run on local thread, we shouldn't pay these cost, and suffer these limit. 

Those bounds should only need when  use `Scheduler` to switch thread.

In other hand, looks like every operator always run in a same thread except `observe_on`. So we needn't share data between threads, data races can be avoid.

So we need to redesign `RawSubscribable`:

```rust
pub trait RawSubscribable<S>
where
  S: Subscribe,
{
  /// a type implemented [`Subscription`]
  type Unsub;

  fn raw_subscribe(self, subscribe: S) -> Self::Unsub;
}
```
We let `subscribe` to be a generic type, so when we implement an operator we can  add `Send` bound to `subscribe` or not. Only  If the `subscribe` and upstream/downstream satisfied `Send` it can switch to another thread.

**Comment by pickfire** [comment]
Is it good to put like `RefCell` everywhere? Shouldn't we differentiate between subjects that only have one subscriber and subjects that have multiple subscribers? Like the difference between `Rc` and `Arc`?

**Comment by M-Adoo** [comment]
You are right, a single version subject we can implement.
