### ISSUE TITLE
Use functions instead of macros.

### ISSUE THREAD

**Issue by cfeitong** [M-Adoo/rxRust#23]
Macros are unfriendly to IDEs. Is it possible to make `from_iter`,  `from_future`, `of` and `empty`  functions?

**Comment by M-Adoo** [comment]
Maybe it possible, I need to think more.

Use macro to crate an Observable is an easy way to keep all type information. That let we know if the closure is satisfied `Send`,`Clone` or `Sync` in the future use.

**Comment by M-Adoo** [comment]
closed by #27
